spring:
  application:
    name: Eureka

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    lease-renewal-interval-in-seconds: 5
    hostname: eureka
