server:
  port: 8060

management:
  endpoints:
    web:
      exposure:
        include: "*"

folders:
  name:
    - D:\项目\ShopMall-3.0\Server\File-Server\src\main\resources\static\tmp0
    - D:\项目\ShopMall-3.0\Server\File-Server\src\main\resources\static\tmp1

quartz:
  scheduler:
    deleteFile: # 0/30 0 9,18 * * ?
      expression: 0/30 * * * * ?

fdfs:
  so-timeout: 30000
  connect-timeout: 20000
  thumb-image:
    width: 200
    height: 200
    format: png
  tracker-list:
    - 192.168.50.70:22122
  web-server-url: http://www.fatdog.shit:8888/

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

swagger:
  enable: true