server:
  port: 8060

spring:
  application:
    name: File-Server
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms

management:
  endpoints:
    web:
      exposure:
        include: "*"

folders:
  name:
    - D:\项目\ShopMall-3.0\Server\File-Server\src\main\resources\static\tmp0
    - D:\项目\ShopMall-3.0\Server\File-Server\src\main\resources\static\tmp1

deleteFileKey: readyToDelete

quartz:
  scheduler:
    deleteFile: # 0/30 0 9,18 * * ?
      expression: 0/30 * * * * ?

fdfs:
  so-timeout: 30000
  connect-timeout: 20000
  thumb-image:
    width: 200
    height: 200
    format: png
  tracker-list:
    - 192.168.241.231:22122
  web-server-url: http://192.168.241.231:8888/

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8020/oauth/token
      user-authorization-uri: http://localhost:8020/oauth/authorize
    resource:
      token-info-uri: http://localhost:8020/oauth/check_token
      user-info-uri: http://localhost:8020/user

swagger:
  enable: true