server:
  port: 80

#zuul:
#  routes:
#    route1:
#      path: /Goods/**
#      serviceId: Goods-Server
#      sensitiveHeaders:
#    route2:
#      path: /User/**
#      serviceId: User-Server
#      sensitiveHeaders:
#    route3:
#      path: /ShopCar/**
#      serviceId: ShopCar-Server
#      sensitiveHeaders:
#    route4:
#      path: /Search/**
#      serviceId: Search-Server
#      sensitiveHeaders:
#    route5:
#      path: /QA/**
#      serviceId: QA-Server
#      sensitiveHeaders:
#  # url方式,超时熔断
#  #host:
#  #  socket-timeout-millis: 2000
#  #  connect-timeout-millis: 4000
## serviceId路由方式超时配置
#ribbon:
#  ReadTimeout: 5000
#  SocketTimeout: 3000
#spring:
#  zipkin:
#    base-url: http://127.0.0.1:9411
#  sleuth:
#    sampler:
#      rate: 1
#logging:
#  level:
#    root: INFO
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
## 熔断时间5s => 解决第一次调用超时失败问题
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#    #default:
#      #execution:
#      #  timeout:
#      #    enabled: false
