server:
  port: 80

spring:
  application:
    name:  User-Client
  zipkin:
    base-url: http://127.0.0.1:9411
  sleuth:
    sampler:
      rate: 1
  servlet:
    multipart:
      enabled: true
      max-request-size: 2048MB
      max-file-size: 2048MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms

zuul:
  routes:
    route1:
      path: /Goods/**
      serviceId: Goods-Server
      sensitiveHeaders:
    route2:
      path: /User/**
      serviceId: User-Server
      sensitiveHeaders:
    route3:
      path: /ShopCar/**
      serviceId: ShopCar-Server
      sensitiveHeaders:
    route4:
      path: /Search/**
      serviceId: Search-Server
      sensitiveHeaders:
    route5:
      path: /QA/**
      serviceId: QA-Server
      sensitiveHeaders:
    route6:
      path: /File/**
      serviceId: File-Server
      sensitiveHeaders:
  # url方式,超时熔断
  #host:
  #  socket-timeout-millis: 2000
  #  connect-timeout-millis: 4000
# serviceId路由方式超时配置
# 大文件上传, 这个超时加大力度
File-Server:
  ribbon:
    ReadTimeout: 60000
    SocketTimeout: 10000

# 默认下游服务超时时间配置
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
# 熔断时间5s => 解决第一次调用超时失败问题
hystrix:
  command:
    File-Server:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: ERROR
    org.springframework.web.servlet.DispatcherServlet: DEBUG